### ISSUE TITLE
build warning Controller.java Some input files use unchecked or unsafe operations.

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/downloadclient#26] opened 2016-05-25 19:21 UTC
downloadclient/src/main/java/de/bayern/gdi/gui/Controller.java: Some input files use unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.

when building with 
mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/share/java/maven
Java version: 1.8.0_91, vendor: Oracle Corporation

should be checked and potentially fixed.

**Comment by dmth** [comment] 2016-06-10 12:07
Does this issue still exist?

**Comment by s-l-teichmann** [comment] 2016-06-10 12:33
They do and they all still related to the FX stuff.

**Comment by dmth** [comment] 2016-09-26 10:44
I'm building with

```
mvn -version                                                                                                                                                        :(
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
```

And cannot reproduce this issue. Is it fixed now?

**Comment by dmth** [comment] 2017-02-24 09:49
I'm closing this issue as I cannot reproduce it.

**Closed as completed by dmth** 2017-02-24 09:49 UTC
